<?xml version="1.0" encoding="UTF-8"?>
<!--
*******************************************************
*******************************************************

          READ ME

*******************************************************

CityGML 2.0 Test dataset "Alderaan"
with Energy ADE 3.0 Beta 7

Last update: 2025-10-14

** Energy ADE 3.0 **

This file contains:
- 1 first-level UrbanFunctionArea object, which contains
- 6 second-level UrbanFunctionArea objects, which contain
- 24 third-level UrbanFunctionArea objects

Each UrbanFunctionArea object is represented via a MultiSurface
and a referencePoint.

The first-level UrbanFunctionArea object has 1 in-line
Appearance (commented out).
The same appearance of Level 1 is copied into the global
appearance.
The second- and third-level UrbanFunctionArea
objects share the global appearance, too.

Some UrbanFunctionArea objects are linked to Water
and Energy objects (from Resources).

** Additional information

To visualise the data and explore the attributes,
you can use the freeware KIT ModelViewer.
You can download it from:

https://www.iai.kit.edu/1302.php

Please be aware that this dataset is intended for
testing purposes, so some attribute values might be
wrong or without any realistic physical meaning.

*******************************************************

This CityGML file was generated by:

Dr. Giorgio Agugiaro
3D Geoinformation group
Delft University of Technology
The Netherlands

https://3d.bk.tudelft.nl/gagugiaro/

*******************************************************
*******************************************************
-->
<core:CityModel xmlns:app="http://www.opengis.net/citygml/appearance/2.0" xmlns:bldg="http://www.opengis.net/citygml/building/2.0" xmlns:brid="http://www.opengis.net/citygml/bridge/2.0" xmlns:core="http://www.opengis.net/citygml/2.0" xmlns:dem="http://www.opengis.net/citygml/relief/2.0" xmlns:frn="http://www.opengis.net/citygml/cityfurniture/2.0" xmlns:gen="http://www.opengis.net/citygml/generics/2.0" xmlns:gml="http://www.opengis.net/gml" xmlns:grp="http://www.opengis.net/citygml/cityobjectgroup/2.0" xmlns:luse="http://www.opengis.net/citygml/landuse/2.0" xmlns:nrg3="http://www.citygml.org/ade/energy/3.0" xmlns:pbase="http://www.opengis.net/citygml/profiles/base/2.0" xmlns:sch="http://www.ascc.net/xml/schematron" xmlns:smil20="http://www.w3.org/2001/SMIL20/" xmlns:smil20lang="http://www.w3.org/2001/SMIL20/Language" xmlns:tex="http://www.opengis.net/citygml/texturedsurface/2.0" xmlns:tran="http://www.opengis.net/citygml/transportation/2.0" xmlns:tun="http://www.opengis.net/citygml/tunnel/2.0" xmlns:veg="http://www.opengis.net/citygml/vegetation/2.0" xmlns:wtr="http://www.opengis.net/citygml/waterbody/2.0" xmlns:xAL="urn:oasis:names:tc:ciq:xsdschema:xAL:2.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<gml:boundedBy>
		<gml:Envelope srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
			<gml:lowerCorner>-80 -100 0</gml:lowerCorner>
			<gml:upperCorner>160 100 0</gml:upperCorner>
		</gml:Envelope>
	</gml:boundedBy>
	<core:cityObjectMember>
		<nrg3:UrbanFunctionArea gml:id="id_urban_function_area_1">
			<gml:description>This is an UrbanFunctionArea of first level</gml:description>
			<gml:name>UrbanFunctionArea of first level</gml:name>
			<nrg3:referencePoint>
				<gml:Point srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
					<gml:pos>40 0 0</gml:pos>
				</gml:Point>
			</nrg3:referencePoint>
			<nrg3:resource>
				<nrg3:Energy gml:id="id_uaf_res_energy_1">
					<gml:description>This is EnergyDemand 1 of id_urban_function_area_1</gml:description>
					<gml:name>Energy 1</gml:name>
					<nrg3:status>actual</nrg3:status>
					<nrg3:operationType codeSpace="resource-oper_codespace_1">demands</nrg3:operationType>
					<nrg3:amountType codeSpace="amnt_type_codespace_1">measurement</nrg3:amountType>
					<nrg3:year>2023</nrg3:year>
					<nrg3:amount uom="kWh/a">1000</nrg3:amount>
					<nrg3:isAmountNormalized>false</nrg3:isAmountNormalized>
					<nrg3:co2Equivalent uom="kg/a">12</nrg3:co2Equivalent>
					<nrg3:costsMoney uom="Euro">50</nrg3:costsMoney>
					<nrg3:yieldsMoney uom="Euro">0</nrg3:yieldsMoney>
					<nrg3:type codeSpace="eng_type_codespace_1">primary</nrg3:type>
					<nrg3:endUse codeSpace="nrg_enduse_codespace_1">electricalAppliances</nrg3:endUse>
					<nrg3:energyCarrier codeSpace="nrg_carrier_codespace_1">electricity</nrg3:energyCarrier>
					<nrg3:maximumLoad uom="kW">4</nrg3:maximumLoad>
					<nrg3:source codeSpace="nrg_source_codespace_1">powerGrid</nrg3:source>
				</nrg3:Energy>
			</nrg3:resource>
			<nrg3:resource>
				<nrg3:Water gml:id="id_uaf_res_water_1">
					<gml:description>This is WaterDemand 1 of id_urban_function_area_1</gml:description>
					<gml:name>WaterDemand 1</gml:name>
					<nrg3:status>actual</nrg3:status>
					<nrg3:operationType codeSpace="resource-oper_codespace_13">demands</nrg3:operationType>
					<nrg3:amountType codeSpace="amnt_type_codespace_13">calibratedSimulation</nrg3:amountType>
					<nrg3:year>2023</nrg3:year>
					<nrg3:amount uom="m3/a">33</nrg3:amount>
					<nrg3:isAmountNormalized>false</nrg3:isAmountNormalized>
					<nrg3:costsMoney uom="Euro">21</nrg3:costsMoney>
					<nrg3:yieldsMoney uom="Euro">6</nrg3:yieldsMoney>
					<nrg3:type codeSpace="wat_type_codespace_7">drinkWater</nrg3:type>
					<nrg3:endUse codeSpace="wat_enduse_codespace_7">washing</nrg3:endUse>
				</nrg3:Water>
			</nrg3:resource>
<!-- BEGIN Please note: local appearances are not supported by FME -->
<!-- 			<app:appearance>
				<app:Appearance gml:id="id_app_urbanfunction_areas_2">
					<gml:description>This is an in-line appearance, associated with the UrbanFunctionArea of rank 1</gml:description>
					<app:theme>UrbanFunctionAreas</app:theme>
					<app:surfaceDataMember>
						<app:X3DMaterial gml:id="X3DMaterial_UUID_7da34b5f-0dc6-4829-8088-6f73a3007b6d">
							<gml:name>SurfaceData UrbanFunctionArea yellow BACK</gml:name>
							<app:isFront>false</app:isFront>
							<app:diffuseColor>1 1 0</app:diffuseColor>
							<app:target>#id_MultiSurf_ufa_1</app:target>
						</app:X3DMaterial>
					</app:surfaceDataMember>
					<app:surfaceDataMember>
						<app:X3DMaterial gml:id="X3DMaterial_UUID_8da34b5f-0da6-4829-8088-6f73a3007b6d">
							<gml:name>SurfaceData UrbanFunctionArea yellow FRONT</gml:name>
							<app:isFront>true</app:isFront>
							<app:diffuseColor>1 1 0</app:diffuseColor>
							<app:target>#id_MultiSurf_ufa_1</app:target>
						</app:X3DMaterial>
					</app:surfaceDataMember>
				</app:Appearance>
			</app:appearance> -->
<!-- END Please note: local appearances are not supported by FME -->
			<grp:class>UrbanFuncionArea_class</grp:class>
			<grp:function>UrbanFuncionArea_function</grp:function>
			<grp:usage>UrbanFuncionArea_usage</grp:usage>
			<grp:groupMember>
				<nrg3:UrbanFunctionArea gml:id="id_urban_function_area_1_1">
					<gml:description>This is an UrbanFunctionArea of second level</gml:description>
					<gml:name>UrbanFunctionArea of second level</gml:name>
					<nrg3:referencePoint>
						<gml:Point srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
							<gml:pos>-40 50 0</gml:pos>
						</gml:Point>
					</nrg3:referencePoint>
					<grp:class>UrbanFuncionArea_class</grp:class>
					<grp:function>UrbanFuncionArea_function</grp:function>
					<grp:usage>UrbanFuncionArea_usage</grp:usage>
					<grp:groupMember>
						<nrg3:UrbanFunctionArea gml:id="id_urban_function_area_1_1_1">
							<gml:description>This is an UrbanFunctionArea of third level</gml:description>
							<gml:name>UrbanFunctionArea of third level</gml:name>
							<nrg3:referencePoint>
								<gml:Point srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
									<gml:pos>-20 25 0</gml:pos>
								</gml:Point>
							</nrg3:referencePoint>
							<grp:class>UrbanFuncionArea_class</grp:class>
							<grp:function>UrbanFuncionArea_function</grp:function>
							<grp:usage>UrbanFuncionArea_usage</grp:usage>
							<grp:geometry>
								<gml:MultiSurface gml:id="id_MultiSurf_ufa_1_1_1" srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
									<gml:surfaceMember>
										<gml:Polygon>
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>-40 0 0 0 0 0 0 50 0 -40 50 0 -40 0 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
								</gml:MultiSurface>
							</grp:geometry>
							<nrg3:type codeSpace="urbfuncarea_type_codeSpace">urbfuncarea_type_13</nrg3:type>
							<nrg3:code codeSpace="urbfuncarea_code_codeSpace">urbfuncarea_code_13</nrg3:code>
						</nrg3:UrbanFunctionArea>
					</grp:groupMember>
					<grp:groupMember>
						<nrg3:UrbanFunctionArea gml:id="id_urban_function_area_1_1_2">
							<gml:description>This is an UrbanFunctionArea of third level</gml:description>
							<gml:name>UrbanFunctionArea of third level</gml:name>
							<nrg3:referencePoint>
								<gml:Point srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
									<gml:pos>-60 75 0</gml:pos>
								</gml:Point>
							</nrg3:referencePoint>
							<grp:class>UrbanFuncionArea_class</grp:class>
							<grp:function>UrbanFuncionArea_function</grp:function>
							<grp:usage>UrbanFuncionArea_usage</grp:usage>
							<grp:geometry>
								<gml:MultiSurface gml:id="id_MultiSurf_ufa_1_1_2" srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
									<gml:surfaceMember>
										<gml:Polygon>
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>-80 50 0 -40 50 0 -40 100 0 -80 100 0 -80 50 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
								</gml:MultiSurface>
							</grp:geometry>
							<nrg3:type codeSpace="urbfuncarea_type_codeSpace">urbfuncarea_type_13</nrg3:type>
							<nrg3:code codeSpace="urbfuncarea_code_codeSpace">urbfuncarea_code_13</nrg3:code>
						</nrg3:UrbanFunctionArea>
					</grp:groupMember>
					<grp:groupMember>
						<nrg3:UrbanFunctionArea gml:id="id_urban_function_area_1_1_3">
							<gml:description>This is an UrbanFunctionArea of third level</gml:description>
							<gml:name>UrbanFunctionArea of third level</gml:name>
							<nrg3:referencePoint>
								<gml:Point srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
									<gml:pos>-20 75 0</gml:pos>
								</gml:Point>
							</nrg3:referencePoint>
							<grp:class>UrbanFuncionArea_class</grp:class>
							<grp:function>UrbanFuncionArea_function</grp:function>
							<grp:usage>UrbanFuncionArea_usage</grp:usage>
							<grp:geometry>
								<gml:MultiSurface gml:id="id_MultiSurf_ufa_1_1_3" srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
									<gml:surfaceMember>
										<gml:Polygon>
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>-40 50 0 0 50 0 0 100 0 -40 100 0 -40 50 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
								</gml:MultiSurface>
							</grp:geometry>
							<nrg3:type codeSpace="urbfuncarea_type_codeSpace">urbfuncarea_type_13</nrg3:type>
							<nrg3:code codeSpace="urbfuncarea_code_codeSpace">urbfuncarea_code_13</nrg3:code>
						</nrg3:UrbanFunctionArea>
					</grp:groupMember>
					<grp:groupMember>
						<nrg3:UrbanFunctionArea gml:id="id_urban_function_area_1_1_4">
							<gml:description>This is an UrbanFunctionArea of third level</gml:description>
							<gml:name>UrbanFunctionArea of third level</gml:name>
							<nrg3:referencePoint>
								<gml:Point srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
									<gml:pos>-60 25 0</gml:pos>
								</gml:Point>
							</nrg3:referencePoint>
							<grp:class>UrbanFuncionArea_class</grp:class>
							<grp:function>UrbanFuncionArea_function</grp:function>
							<grp:usage>UrbanFuncionArea_usage</grp:usage>
							<grp:geometry>
								<gml:MultiSurface gml:id="id_MultiSurf_ufa_1_1_4" srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
									<gml:surfaceMember>
										<gml:Polygon>
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>-80 0 0 -40 0 0 -40 50 0 -80 50 0 -80 0 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
								</gml:MultiSurface>
							</grp:geometry>
							<nrg3:type codeSpace="urbfuncarea_type_codeSpace">urbfuncarea_type_13</nrg3:type>
							<nrg3:code codeSpace="urbfuncarea_code_codeSpace">urbfuncarea_code_13</nrg3:code>
						</nrg3:UrbanFunctionArea>
					</grp:groupMember>
					<grp:geometry>
						<gml:MultiSurface gml:id="id_MultiSurf_ufa_1_1" srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
							<gml:surfaceMember>
								<gml:Polygon>
									<gml:exterior>
										<gml:LinearRing>
											<gml:posList>-80 0 0 0 0 0 0 100 0 -80 100 0 -80 0 0</gml:posList>
										</gml:LinearRing>
									</gml:exterior>
								</gml:Polygon>
							</gml:surfaceMember>
						</gml:MultiSurface>
					</grp:geometry>
					<nrg3:type codeSpace="urbfuncarea_type_codeSpace">urbfuncarea_type_12</nrg3:type>
					<nrg3:code codeSpace="urbfuncarea_code_codeSpace">urbfuncarea_code_12</nrg3:code>
				</nrg3:UrbanFunctionArea>
			</grp:groupMember>
			<grp:groupMember>
				<nrg3:UrbanFunctionArea gml:id="id_urban_function_area_1_2">
					<gml:description>This is an UrbanFunctionArea of second level</gml:description>
					<gml:name>UrbanFunctionArea of second level</gml:name>
					<nrg3:referencePoint>
						<gml:Point srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
							<gml:pos>40 50 0</gml:pos>
						</gml:Point>
					</nrg3:referencePoint>
					<grp:class>UrbanFuncionArea_class</grp:class>
					<grp:function>UrbanFuncionArea_function</grp:function>
					<grp:usage>UrbanFuncionArea_usage</grp:usage>
					<grp:groupMember>
						<nrg3:UrbanFunctionArea gml:id="id_urban_function_area_1_2_1">
							<gml:description>This is an UrbanFunctionArea of third level</gml:description>
							<gml:name>UrbanFunctionArea of third level</gml:name>
							<nrg3:referencePoint>
								<gml:Point srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
									<gml:pos>20 75 0</gml:pos>
								</gml:Point>
							</nrg3:referencePoint>
							<grp:class>UrbanFuncionArea_class</grp:class>
							<grp:function>UrbanFuncionArea_function</grp:function>
							<grp:usage>UrbanFuncionArea_usage</grp:usage>
							<grp:geometry>
								<gml:MultiSurface gml:id="id_MultiSurf_ufa_1_2_1" srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
									<gml:surfaceMember>
										<gml:Polygon>
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>0 50 0 40 50 0 40 100 0 0 100 0 0 50 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
								</gml:MultiSurface>
							</grp:geometry>
							<nrg3:type codeSpace="urbfuncarea_type_codeSpace">urbfuncarea_type_13</nrg3:type>
							<nrg3:code codeSpace="urbfuncarea_code_codeSpace">urbfuncarea_code_13</nrg3:code>
						</nrg3:UrbanFunctionArea>
					</grp:groupMember>
					<grp:groupMember>
						<nrg3:UrbanFunctionArea gml:id="id_urban_function_area_1_2_2">
							<gml:description>This is an UrbanFunctionArea of third level</gml:description>
							<gml:name>UrbanFunctionArea of third level</gml:name>
							<nrg3:referencePoint>
								<gml:Point srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
									<gml:pos>60 75 0</gml:pos>
								</gml:Point>
							</nrg3:referencePoint>
							<grp:class>UrbanFuncionArea_class</grp:class>
							<grp:function>UrbanFuncionArea_function</grp:function>
							<grp:usage>UrbanFuncionArea_usage</grp:usage>
							<grp:geometry>
								<gml:MultiSurface gml:id="id_MultiSurf_ufa_1_2_2" srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
									<gml:surfaceMember>
										<gml:Polygon>
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>40 50 0 80 50 0 80 100 0 40 100 0 40 50 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
								</gml:MultiSurface>
							</grp:geometry>
							<nrg3:type codeSpace="urbfuncarea_type_codeSpace">urbfuncarea_type_13</nrg3:type>
							<nrg3:code codeSpace="urbfuncarea_code_codeSpace">urbfuncarea_code_13</nrg3:code>
						</nrg3:UrbanFunctionArea>
					</grp:groupMember>
					<grp:groupMember>
						<nrg3:UrbanFunctionArea gml:id="id_urban_function_area_1_2_3">
							<gml:description>This is an UrbanFunctionArea of third level</gml:description>
							<gml:name>UrbanFunctionArea of third level</gml:name>
							<nrg3:referencePoint>
								<gml:Point srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
									<gml:pos>20 25 0</gml:pos>
								</gml:Point>
							</nrg3:referencePoint>
							<grp:class>UrbanFuncionArea_class</grp:class>
							<grp:function>UrbanFuncionArea_function</grp:function>
							<grp:usage>UrbanFuncionArea_usage</grp:usage>
							<grp:geometry>
								<gml:MultiSurface gml:id="id_MultiSurf_ufa_1_2_3" srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
									<gml:surfaceMember>
										<gml:Polygon>
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>0 0 0 40 0 0 40 50 0 0 50 0 0 0 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
								</gml:MultiSurface>
							</grp:geometry>
							<nrg3:type codeSpace="urbfuncarea_type_codeSpace">urbfuncarea_type_13</nrg3:type>
							<nrg3:code codeSpace="urbfuncarea_code_codeSpace">urbfuncarea_code_13</nrg3:code>
						</nrg3:UrbanFunctionArea>
					</grp:groupMember>
					<grp:groupMember>
						<nrg3:UrbanFunctionArea gml:id="id_urban_function_area_1_2_4">
							<gml:description>This is an UrbanFunctionArea of third level</gml:description>
							<gml:name>UrbanFunctionArea of third level</gml:name>
							<nrg3:referencePoint>
								<gml:Point srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
									<gml:pos>60 25 0</gml:pos>
								</gml:Point>
							</nrg3:referencePoint>
							<grp:class>UrbanFuncionArea_class</grp:class>
							<grp:function>UrbanFuncionArea_function</grp:function>
							<grp:usage>UrbanFuncionArea_usage</grp:usage>
							<grp:geometry>
								<gml:MultiSurface gml:id="id_MultiSurf_ufa_1_2_4" srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
									<gml:surfaceMember>
										<gml:Polygon>
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>40 0 0 80 0 0 80 50 0 40 50 0 40 0 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
								</gml:MultiSurface>
							</grp:geometry>
							<nrg3:type codeSpace="urbfuncarea_type_codeSpace">urbfuncarea_type_13</nrg3:type>
							<nrg3:code codeSpace="urbfuncarea_code_codeSpace">urbfuncarea_code_13</nrg3:code>
						</nrg3:UrbanFunctionArea>
					</grp:groupMember>
					<grp:geometry>
						<gml:MultiSurface gml:id="id_MultiSurf_ufa_1_2" srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
							<gml:surfaceMember>
								<gml:Polygon>
									<gml:exterior>
										<gml:LinearRing>
											<gml:posList>0 0 0 80 0 0 80 100 0 0 100 0 0 0 0</gml:posList>
										</gml:LinearRing>
									</gml:exterior>
								</gml:Polygon>
							</gml:surfaceMember>
						</gml:MultiSurface>
					</grp:geometry>
					<nrg3:type codeSpace="urbfuncarea_type_codeSpace">urbfuncarea_type_12</nrg3:type>
					<nrg3:code codeSpace="urbfuncarea_code_codeSpace">urbfuncarea_code_12</nrg3:code>
				</nrg3:UrbanFunctionArea>
			</grp:groupMember>
			<grp:groupMember>
				<nrg3:UrbanFunctionArea gml:id="id_urban_function_area_1_3">
					<gml:description>This is an UrbanFunctionArea of second level</gml:description>
					<gml:name>UrbanFunctionArea of second level</gml:name>
					<nrg3:referencePoint>
						<gml:Point srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
							<gml:pos>120 50 0</gml:pos>
						</gml:Point>
					</nrg3:referencePoint>
					<nrg3:resource>
						<nrg3:Energy gml:id="id_uaf_res_energy_2">
							<gml:description>This is EnergyDemand 2 of id_urban_function_area_1_3</gml:description>
							<gml:name>Energy 2</gml:name>
							<nrg3:status>actual</nrg3:status>
							<nrg3:operationType codeSpace="resource-oper_codespace_1">demands</nrg3:operationType>
							<nrg3:amountType codeSpace="amnt_type_codespace_1">calibratedSimulation</nrg3:amountType>
							<nrg3:year>2023</nrg3:year>
							<nrg3:amount uom="kWh/a">50</nrg3:amount>
							<nrg3:isAmountNormalized>false</nrg3:isAmountNormalized>
							<nrg3:co2Equivalent uom="kg/a">1</nrg3:co2Equivalent>
							<nrg3:costsMoney uom="Euro">56</nrg3:costsMoney>
							<nrg3:yieldsMoney uom="Euro">2</nrg3:yieldsMoney>
							<nrg3:type codeSpace="eng_type_codespace_1">primary</nrg3:type>
							<nrg3:endUse codeSpace="nrg_enduse_codespace_1">heating</nrg3:endUse>
							<nrg3:energyCarrier codeSpace="nrg_carrier_codespace_1">electricity</nrg3:energyCarrier>
							<nrg3:maximumLoad uom="kW">4</nrg3:maximumLoad>
							<nrg3:source codeSpace="nrg_source_codespace_1">powerGrid</nrg3:source>
						</nrg3:Energy>
					</nrg3:resource>
					<nrg3:resource>
						<nrg3:Energy gml:id="id_uaf_res_energy_3">
							<gml:description>This is EnergyDemand 3 of id_urban_function_area_1_3</gml:description>
							<gml:name>Energy 3</gml:name>
							<nrg3:status>actual</nrg3:status>
							<nrg3:operationType codeSpace="resource-oper_codespace_1">demands</nrg3:operationType>
							<nrg3:amountType codeSpace="amnt_type_codespace_1">measurement</nrg3:amountType>
							<nrg3:year>2023</nrg3:year>
							<nrg3:amount uom="kWh/a">200</nrg3:amount>
							<nrg3:isAmountNormalized>false</nrg3:isAmountNormalized>
							<nrg3:co2Equivalent uom="kg/a">5</nrg3:co2Equivalent>
							<nrg3:costsMoney uom="Euro">12</nrg3:costsMoney>
							<nrg3:yieldsMoney uom="Euro">5</nrg3:yieldsMoney>
							<nrg3:type codeSpace="eng_type_codespace_1">primary</nrg3:type>
							<nrg3:endUse codeSpace="nrg_enduse_codespace_1">cooking</nrg3:endUse>
							<nrg3:energyCarrier codeSpace="nrg_carrier_codespace_1">electricity</nrg3:energyCarrier>
							<nrg3:maximumLoad uom="kW">4</nrg3:maximumLoad>
							<nrg3:source codeSpace="nrg_source_codespace_1">powerGrid</nrg3:source>
						</nrg3:Energy>
					</nrg3:resource>
					<grp:class>UrbanFuncionArea_class</grp:class>
					<grp:function>UrbanFuncionArea_function</grp:function>
					<grp:usage>UrbanFuncionArea_usage</grp:usage>
					<grp:groupMember>
						<nrg3:UrbanFunctionArea gml:id="id_urban_function_area_1_3_1">
							<gml:description>This is an UrbanFunctionArea of third level</gml:description>
							<gml:name>UrbanFunctionArea of third level</gml:name>
							<nrg3:referencePoint>
								<gml:Point srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
									<gml:pos>140 75 0</gml:pos>
								</gml:Point>
							</nrg3:referencePoint>
							<nrg3:resource>
								<nrg3:Energy gml:id="id_uaf_res_energy_4">
									<gml:description>This is EnergyDemand 4 of id_urban_function_area_1_3_1</gml:description>
									<gml:name>Energy 4</gml:name>
									<nrg3:status>actual</nrg3:status>
									<nrg3:operationType codeSpace="resource-oper_codespace_1">demands</nrg3:operationType>
									<nrg3:amountType codeSpace="amnt_type_codespace_1">measurement</nrg3:amountType>
									<nrg3:year>2023</nrg3:year>
									<nrg3:amount uom="kWh/a">3200</nrg3:amount>
									<nrg3:isAmountNormalized>false</nrg3:isAmountNormalized>
									<nrg3:co2Equivalent uom="kg/a">45</nrg3:co2Equivalent>
									<nrg3:costsMoney uom="Euro">112</nrg3:costsMoney>
									<nrg3:yieldsMoney uom="Euro">53</nrg3:yieldsMoney>
									<nrg3:type codeSpace="eng_type_codespace_1">primary</nrg3:type>
									<nrg3:endUse codeSpace="nrg_enduse_codespace_1">cooling</nrg3:endUse>
									<nrg3:energyCarrier codeSpace="nrg_carrier_codespace_1">electricity</nrg3:energyCarrier>
									<nrg3:maximumLoad uom="kW">4</nrg3:maximumLoad>
									<nrg3:source codeSpace="nrg_source_codespace_1">powerGrid</nrg3:source>
								</nrg3:Energy>
							</nrg3:resource>
							<grp:class>UrbanFuncionArea_class</grp:class>
							<grp:function>UrbanFuncionArea_function</grp:function>
							<grp:usage>UrbanFuncionArea_usage</grp:usage>
							<grp:geometry>
								<gml:MultiSurface gml:id="id_MultiSurf_ufa_1_3_1" srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
									<gml:surfaceMember>
										<gml:Polygon>
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>120 50 0 160 50 0 160 100 0 120 100 0 120 50 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
								</gml:MultiSurface>
							</grp:geometry>
							<nrg3:type codeSpace="urbfuncarea_type_codeSpace">urbfuncarea_type_13</nrg3:type>
							<nrg3:code codeSpace="urbfuncarea_code_codeSpace">urbfuncarea_code_13</nrg3:code>
						</nrg3:UrbanFunctionArea>
					</grp:groupMember>
					<grp:groupMember>
						<nrg3:UrbanFunctionArea gml:id="id_urban_function_area_1_3_2">
							<gml:description>This is an UrbanFunctionArea of third level</gml:description>
							<gml:name>UrbanFunctionArea of third level</gml:name>
							<nrg3:referencePoint>
								<gml:Point srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
									<gml:pos>100 75 0</gml:pos>
								</gml:Point>
							</nrg3:referencePoint>
							<grp:class>UrbanFuncionArea_class</grp:class>
							<grp:function>UrbanFuncionArea_function</grp:function>
							<grp:usage>UrbanFuncionArea_usage</grp:usage>
							<grp:geometry>
								<gml:MultiSurface gml:id="id_MultiSurf_ufa_1_3_2" srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
									<gml:surfaceMember>
										<gml:Polygon>
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>80 50 0 120 50 0 120 100 0 80 100 0 80 50 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
								</gml:MultiSurface>
							</grp:geometry>
							<nrg3:type codeSpace="urbfuncarea_type_codeSpace">urbfuncarea_type_13</nrg3:type>
							<nrg3:code codeSpace="urbfuncarea_code_codeSpace">urbfuncarea_code_13</nrg3:code>
						</nrg3:UrbanFunctionArea>
					</grp:groupMember>
					<grp:groupMember>
						<nrg3:UrbanFunctionArea gml:id="id_urban_function_area_1_3_3">
							<gml:description>This is an UrbanFunctionArea of third level</gml:description>
							<gml:name>UrbanFunctionArea of third level</gml:name>
							<nrg3:referencePoint>
								<gml:Point srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
									<gml:pos>140 25 0</gml:pos>
								</gml:Point>
							</nrg3:referencePoint>
							<grp:class>UrbanFuncionArea_class</grp:class>
							<grp:function>UrbanFuncionArea_function</grp:function>
							<grp:usage>UrbanFuncionArea_usage</grp:usage>
							<grp:geometry>
								<gml:MultiSurface gml:id="id_MultiSurf_ufa_1_3_3" srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
									<gml:surfaceMember>
										<gml:Polygon>
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>120 0 0 160 0 0 160 50 0 120 50 0 120 0 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
								</gml:MultiSurface>
							</grp:geometry>
							<nrg3:type codeSpace="urbfuncarea_type_codeSpace">urbfuncarea_type_13</nrg3:type>
							<nrg3:code codeSpace="urbfuncarea_code_codeSpace">urbfuncarea_code_13</nrg3:code>
						</nrg3:UrbanFunctionArea>
					</grp:groupMember>
					<grp:groupMember>
						<nrg3:UrbanFunctionArea gml:id="id_urban_function_area_1_3_4">
							<gml:description>This is an UrbanFunctionArea of third level</gml:description>
							<gml:name>UrbanFunctionArea of third level</gml:name>
							<nrg3:referencePoint>
								<gml:Point srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
									<gml:pos>100 25 0</gml:pos>
								</gml:Point>
							</nrg3:referencePoint>
							<grp:class>UrbanFuncionArea_class</grp:class>
							<grp:function>UrbanFuncionArea_function</grp:function>
							<grp:usage>UrbanFuncionArea_usage</grp:usage>
							<grp:geometry>
								<gml:MultiSurface gml:id="id_MultiSurf_ufa_1_3_4" srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
									<gml:surfaceMember>
										<gml:Polygon>
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>80 0 0 120 0 0 120 50 0 80 50 0 80 0 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
								</gml:MultiSurface>
							</grp:geometry>
							<nrg3:type codeSpace="urbfuncarea_type_codeSpace">urbfuncarea_type_13</nrg3:type>
							<nrg3:code codeSpace="urbfuncarea_code_codeSpace">urbfuncarea_code_13</nrg3:code>
						</nrg3:UrbanFunctionArea>
					</grp:groupMember>
					<grp:geometry>
						<gml:MultiSurface gml:id="id_MultiSurf_ufa_1_3" srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
							<gml:surfaceMember>
								<gml:Polygon>
									<gml:exterior>
										<gml:LinearRing>
											<gml:posList>80 0 0 160 0 0 160 100 0 80 100 0 80 0 0</gml:posList>
										</gml:LinearRing>
									</gml:exterior>
								</gml:Polygon>
							</gml:surfaceMember>
						</gml:MultiSurface>
					</grp:geometry>
					<nrg3:type codeSpace="urbfuncarea_type_codeSpace">urbfuncarea_type_12</nrg3:type>
					<nrg3:code codeSpace="urbfuncarea_code_codeSpace">urbfuncarea_code_12</nrg3:code>
				</nrg3:UrbanFunctionArea>
			</grp:groupMember>
			<grp:groupMember>
				<nrg3:UrbanFunctionArea gml:id="id_urban_function_area_1_4">
					<gml:description>This is an UrbanFunctionArea of second level</gml:description>
					<gml:name>UrbanFunctionArea of second level</gml:name>
					<nrg3:referencePoint>
						<gml:Point srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
							<gml:pos>-40 -50 0</gml:pos>
						</gml:Point>
					</nrg3:referencePoint>
					<nrg3:resource>
						<nrg3:Water gml:id="id_uaf_res_water_2">
							<gml:description>This is WaterDemand 2 of id_urban_function_area_1_4</gml:description>
							<gml:name>WaterDemand 2</gml:name>
							<nrg3:status>actual</nrg3:status>
							<nrg3:operationType codeSpace="resource-oper_codespace_13">demands</nrg3:operationType>
							<nrg3:amountType codeSpace="amnt_type_codespace_13">calibratedSimulation</nrg3:amountType>
							<nrg3:year>2023</nrg3:year>
							<nrg3:amount uom="m3/a">12</nrg3:amount>
							<nrg3:isAmountNormalized>false</nrg3:isAmountNormalized>
							<nrg3:costsMoney uom="Euro">11</nrg3:costsMoney>
							<nrg3:yieldsMoney uom="Euro">2</nrg3:yieldsMoney>
							<nrg3:type codeSpace="wat_type_codespace_7">drinkWater</nrg3:type>
							<nrg3:endUse codeSpace="wat_enduse_codespace_7">washing</nrg3:endUse>
						</nrg3:Water>
					</nrg3:resource>
					<grp:class>UrbanFuncionArea_class</grp:class>
					<grp:function>UrbanFuncionArea_function</grp:function>
					<grp:usage>UrbanFuncionArea_usage</grp:usage>
					<grp:groupMember>
						<nrg3:UrbanFunctionArea gml:id="id_urban_function_area_1_4_1">
							<gml:description>This is an UrbanFunctionArea of third level</gml:description>
							<gml:name>UrbanFunctionArea of third level</gml:name>
							<nrg3:referencePoint>
								<gml:Point srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
									<gml:pos>-60 -75 0</gml:pos>
								</gml:Point>
							</nrg3:referencePoint>
							<grp:class>UrbanFuncionArea_class</grp:class>
							<grp:function>UrbanFuncionArea_function</grp:function>
							<grp:usage>UrbanFuncionArea_usage</grp:usage>
							<grp:geometry>
								<gml:MultiSurface gml:id="id_MultiSurf_ufa_1_4_1" srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
									<gml:surfaceMember>
										<gml:Polygon>
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>-80 -100 0 -40 -100 0 -40 -50 0 -80 -50 0 -80 -100 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
								</gml:MultiSurface>
							</grp:geometry>
							<nrg3:type codeSpace="urbfuncarea_type_codeSpace">urbfuncarea_type_13</nrg3:type>
							<nrg3:code codeSpace="urbfuncarea_code_codeSpace">urbfuncarea_code_13</nrg3:code>
						</nrg3:UrbanFunctionArea>
					</grp:groupMember>
					<grp:groupMember>
						<nrg3:UrbanFunctionArea gml:id="id_urban_function_area_1_4_2">
							<gml:description>This is an UrbanFunctionArea of third level</gml:description>
							<gml:name>UrbanFunctionArea of third level</gml:name>
							<nrg3:referencePoint>
								<gml:Point srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
									<gml:pos>-60 -25 0</gml:pos>
								</gml:Point>
							</nrg3:referencePoint>
							<grp:class>UrbanFuncionArea_class</grp:class>
							<grp:function>UrbanFuncionArea_function</grp:function>
							<grp:usage>UrbanFuncionArea_usage</grp:usage>
							<grp:geometry>
								<gml:MultiSurface gml:id="id_MultiSurf_ufa_1_4_2" srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
									<gml:surfaceMember>
										<gml:Polygon>
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>-80 -50 0 -40 -50 0 -40 0 0 -80 0 0 -80 -50 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
								</gml:MultiSurface>
							</grp:geometry>
							<nrg3:type codeSpace="urbfuncarea_type_codeSpace">urbfuncarea_type_13</nrg3:type>
							<nrg3:code codeSpace="urbfuncarea_code_codeSpace">urbfuncarea_code_13</nrg3:code>
						</nrg3:UrbanFunctionArea>
					</grp:groupMember>
					<grp:groupMember>
						<nrg3:UrbanFunctionArea gml:id="id_urban_function_area_1_4_3">
							<gml:description>This is an UrbanFunctionArea of third level</gml:description>
							<gml:name>UrbanFunctionArea of third level</gml:name>
							<nrg3:referencePoint>
								<gml:Point srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
									<gml:pos>-20 -75 0</gml:pos>
								</gml:Point>
							</nrg3:referencePoint>
							<grp:class>UrbanFuncionArea_class</grp:class>
							<grp:function>UrbanFuncionArea_function</grp:function>
							<grp:usage>UrbanFuncionArea_usage</grp:usage>
							<grp:geometry>
								<gml:MultiSurface gml:id="id_MultiSurf_ufa_1_4_3" srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
									<gml:surfaceMember>
										<gml:Polygon>
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>-40 -100 0 0 -100 0 0 -50 0 -40 -50 0 -40 -100 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
								</gml:MultiSurface>
							</grp:geometry>
							<nrg3:type codeSpace="urbfuncarea_type_codeSpace">urbfuncarea_type_13</nrg3:type>
							<nrg3:code codeSpace="urbfuncarea_code_codeSpace">urbfuncarea_code_13</nrg3:code>
						</nrg3:UrbanFunctionArea>
					</grp:groupMember>
					<grp:groupMember>
						<nrg3:UrbanFunctionArea gml:id="id_urban_function_area_1_4_4">
							<gml:description>This is an UrbanFunctionArea of third level</gml:description>
							<gml:name>UrbanFunctionArea of third level</gml:name>
							<nrg3:referencePoint>
								<gml:Point srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
									<gml:pos>-20 -25 0</gml:pos>
								</gml:Point>
							</nrg3:referencePoint>
							<grp:class>UrbanFuncionArea_class</grp:class>
							<grp:function>UrbanFuncionArea_function</grp:function>
							<grp:usage>UrbanFuncionArea_usage</grp:usage>
							<grp:geometry>
								<gml:MultiSurface gml:id="id_MultiSurf_ufa_1_4_4" srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
									<gml:surfaceMember>
										<gml:Polygon>
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>-40 -50 0 0 -50 0 0 0 0 -40 0 0 -40 -50 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
								</gml:MultiSurface>
							</grp:geometry>
							<nrg3:type codeSpace="urbfuncarea_type_codeSpace">urbfuncarea_type_13</nrg3:type>
							<nrg3:code codeSpace="urbfuncarea_code_codeSpace">urbfuncarea_code_13</nrg3:code>
						</nrg3:UrbanFunctionArea>
					</grp:groupMember>
					<grp:geometry>
						<gml:MultiSurface gml:id="id_MultiSurf_ufa_1_4" srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
							<gml:surfaceMember>
								<gml:Polygon>
									<gml:exterior>
										<gml:LinearRing>
											<gml:posList>-80 -100 0 0 -100 0 0 0 0 -80 0 0 -80 -100 0</gml:posList>
										</gml:LinearRing>
									</gml:exterior>
								</gml:Polygon>
							</gml:surfaceMember>
						</gml:MultiSurface>
					</grp:geometry>
					<nrg3:type codeSpace="urbfuncarea_type_codeSpace">urbfuncarea_type_12</nrg3:type>
					<nrg3:code codeSpace="urbfuncarea_code_codeSpace">urbfuncarea_code_12</nrg3:code>
				</nrg3:UrbanFunctionArea>
			</grp:groupMember>
			<grp:groupMember>
				<nrg3:UrbanFunctionArea gml:id="id_urban_function_area_1_5">
					<gml:description>This is an UrbanFunctionArea of second level</gml:description>
					<gml:name>UrbanFunctionArea of second level</gml:name>
					<nrg3:referencePoint>
						<gml:Point srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
							<gml:pos>40 -50 0</gml:pos>
						</gml:Point>
					</nrg3:referencePoint>
					<grp:class>UrbanFuncionArea_class</grp:class>
					<grp:function>UrbanFuncionArea_function</grp:function>
					<grp:usage>UrbanFuncionArea_usage</grp:usage>
					<grp:groupMember>
						<nrg3:UrbanFunctionArea gml:id="id_urban_function_area_1_5_1">
							<gml:description>This is an UrbanFunctionArea of third level</gml:description>
							<gml:name>UrbanFunctionArea of third level</gml:name>
							<nrg3:referencePoint>
								<gml:Point srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
									<gml:pos>60 -75 0</gml:pos>
								</gml:Point>
							</nrg3:referencePoint>
							<grp:class>UrbanFuncionArea_class</grp:class>
							<grp:function>UrbanFuncionArea_function</grp:function>
							<grp:usage>UrbanFuncionArea_usage</grp:usage>
							<grp:geometry>
								<gml:MultiSurface gml:id="id_MultiSurf_ufa_1_5_1" srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
									<gml:surfaceMember>
										<gml:Polygon>
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>40 -100 0 80 -100 0 80 -50 0 40 -50 0 40 -100 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
								</gml:MultiSurface>
							</grp:geometry>
							<nrg3:type codeSpace="urbfuncarea_type_codeSpace">urbfuncarea_type_13</nrg3:type>
							<nrg3:code codeSpace="urbfuncarea_code_codeSpace">urbfuncarea_code_13</nrg3:code>
						</nrg3:UrbanFunctionArea>
					</grp:groupMember>
					<grp:groupMember>
						<nrg3:UrbanFunctionArea gml:id="id_urban_function_area_1_5_2">
							<gml:description>This is an UrbanFunctionArea of third level</gml:description>
							<gml:name>UrbanFunctionArea of third level</gml:name>
							<nrg3:referencePoint>
								<gml:Point srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
									<gml:pos>20 -75 0</gml:pos>
								</gml:Point>
							</nrg3:referencePoint>
							<grp:class>UrbanFuncionArea_class</grp:class>
							<grp:function>UrbanFuncionArea_function</grp:function>
							<grp:usage>UrbanFuncionArea_usage</grp:usage>
							<grp:geometry>
								<gml:MultiSurface gml:id="id_MultiSurf_ufa_1_5_2" srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
									<gml:surfaceMember>
										<gml:Polygon>
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>0 -100 0 40 -100 0 40 -50 0 0 -50 0 0 -100 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
								</gml:MultiSurface>
							</grp:geometry>
							<nrg3:type codeSpace="urbfuncarea_type_codeSpace">urbfuncarea_type_13</nrg3:type>
							<nrg3:code codeSpace="urbfuncarea_code_codeSpace">urbfuncarea_code_13</nrg3:code>
						</nrg3:UrbanFunctionArea>
					</grp:groupMember>
					<grp:groupMember>
						<nrg3:UrbanFunctionArea gml:id="id_urban_function_area_1_5_3">
							<gml:description>This is an UrbanFunctionArea of third level</gml:description>
							<gml:name>UrbanFunctionArea of third level</gml:name>
							<nrg3:referencePoint>
								<gml:Point srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
									<gml:pos>60 -25 0</gml:pos>
								</gml:Point>
							</nrg3:referencePoint>
							<grp:class>UrbanFuncionArea_class</grp:class>
							<grp:function>UrbanFuncionArea_function</grp:function>
							<grp:usage>UrbanFuncionArea_usage</grp:usage>
							<grp:geometry>
								<gml:MultiSurface gml:id="id_MultiSurf_ufa_1_5_3" srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
									<gml:surfaceMember>
										<gml:Polygon>
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>40 -50 0 80 -50 0 80 0 0 40 0 0 40 -50 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
								</gml:MultiSurface>
							</grp:geometry>
							<nrg3:type codeSpace="urbfuncarea_type_codeSpace">urbfuncarea_type_13</nrg3:type>
							<nrg3:code codeSpace="urbfuncarea_code_codeSpace">urbfuncarea_code_13</nrg3:code>
						</nrg3:UrbanFunctionArea>
					</grp:groupMember>
					<grp:groupMember>
						<nrg3:UrbanFunctionArea gml:id="id_urban_function_area_1_5_4">
							<gml:description>This is an UrbanFunctionArea of third level</gml:description>
							<gml:name>UrbanFunctionArea of third level</gml:name>
							<nrg3:referencePoint>
								<gml:Point srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
									<gml:pos>20 -25 0</gml:pos>
								</gml:Point>
							</nrg3:referencePoint>
							<grp:class>UrbanFuncionArea_class</grp:class>
							<grp:function>UrbanFuncionArea_function</grp:function>
							<grp:usage>UrbanFuncionArea_usage</grp:usage>
							<grp:geometry>
								<gml:MultiSurface gml:id="id_MultiSurf_ufa_1_5_4" srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
									<gml:surfaceMember>
										<gml:Polygon>
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>0 -50 0 40 -50 0 40 0 0 0 0 0 0 -50 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
								</gml:MultiSurface>
							</grp:geometry>
							<nrg3:type codeSpace="urbfuncarea_type_codeSpace">urbfuncarea_type_13</nrg3:type>
							<nrg3:code codeSpace="urbfuncarea_code_codeSpace">urbfuncarea_code_13</nrg3:code>
						</nrg3:UrbanFunctionArea>
					</grp:groupMember>
					<grp:geometry>
						<gml:MultiSurface gml:id="id_MultiSurf_ufa_1_5" srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
							<gml:surfaceMember>
								<gml:Polygon>
									<gml:exterior>
										<gml:LinearRing>
											<gml:posList>0 -100 0 80 -100 0 80 0 0 0 0 0 0 -100 0</gml:posList>
										</gml:LinearRing>
									</gml:exterior>
								</gml:Polygon>
							</gml:surfaceMember>
						</gml:MultiSurface>
					</grp:geometry>
					<nrg3:type codeSpace="urbfuncarea_type_codeSpace">urbfuncarea_type_12</nrg3:type>
					<nrg3:code codeSpace="urbfuncarea_code_codeSpace">urbfuncarea_code_12</nrg3:code>
				</nrg3:UrbanFunctionArea>
			</grp:groupMember>
			<grp:groupMember>
				<nrg3:UrbanFunctionArea gml:id="id_urban_function_area_1_6">
					<gml:description>This is an UrbanFunctionArea of second level</gml:description>
					<gml:name>UrbanFunctionArea of second level</gml:name>
					<nrg3:referencePoint>
						<gml:Point srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
							<gml:pos>120 -50 0</gml:pos>
						</gml:Point>
					</nrg3:referencePoint>
					<grp:class>UrbanFuncionArea_class</grp:class>
					<grp:function>UrbanFuncionArea_function</grp:function>
					<grp:usage>UrbanFuncionArea_usage</grp:usage>
					<grp:groupMember>
						<nrg3:UrbanFunctionArea gml:id="id_urban_function_area_1_6_1">
							<gml:description>This is an UrbanFunctionArea of third level</gml:description>
							<gml:name>UrbanFunctionArea of third level</gml:name>
							<nrg3:referencePoint>
								<gml:Point srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
									<gml:pos>100 -75 0</gml:pos>
								</gml:Point>
							</nrg3:referencePoint>
							<grp:class>UrbanFuncionArea_class</grp:class>
							<grp:function>UrbanFuncionArea_function</grp:function>
							<grp:usage>UrbanFuncionArea_usage</grp:usage>
							<grp:geometry>
								<gml:MultiSurface gml:id="id_MultiSurf_ufa_1_6_1" srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
									<gml:surfaceMember>
										<gml:Polygon>
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>80 -100 0 120 -100 0 120 -50 0 80 -50 0 80 -100 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
								</gml:MultiSurface>
							</grp:geometry>
							<nrg3:type codeSpace="urbfuncarea_type_codeSpace">urbfuncarea_type_13</nrg3:type>
							<nrg3:code codeSpace="urbfuncarea_code_codeSpace">urbfuncarea_code_13</nrg3:code>
						</nrg3:UrbanFunctionArea>
					</grp:groupMember>
					<grp:groupMember>
						<nrg3:UrbanFunctionArea gml:id="id_urban_function_area_1_6_2">
							<gml:description>This is an UrbanFunctionArea of third level</gml:description>
							<gml:name>UrbanFunctionArea of third level</gml:name>
							<nrg3:referencePoint>
								<gml:Point srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
									<gml:pos>140 -25 0</gml:pos>
								</gml:Point>
							</nrg3:referencePoint>
							<grp:class>UrbanFuncionArea_class</grp:class>
							<grp:function>UrbanFuncionArea_function</grp:function>
							<grp:usage>UrbanFuncionArea_usage</grp:usage>
							<grp:geometry>
								<gml:MultiSurface gml:id="id_MultiSurf_ufa_1_6_2" srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
									<gml:surfaceMember>
										<gml:Polygon>
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>120 -50 0 160 -50 0 160 0 0 120 0 0 120 -50 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
								</gml:MultiSurface>
							</grp:geometry>
							<nrg3:type codeSpace="urbfuncarea_type_codeSpace">urbfuncarea_type_13</nrg3:type>
							<nrg3:code codeSpace="urbfuncarea_code_codeSpace">urbfuncarea_code_13</nrg3:code>
						</nrg3:UrbanFunctionArea>
					</grp:groupMember>
					<grp:groupMember>
						<nrg3:UrbanFunctionArea gml:id="id_urban_function_area_1_6_3">
							<gml:description>This is an UrbanFunctionArea of third level</gml:description>
							<gml:name>UrbanFunctionArea of third level</gml:name>
							<nrg3:referencePoint>
								<gml:Point srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
									<gml:pos>100 -25 0</gml:pos>
								</gml:Point>
							</nrg3:referencePoint>
							<grp:class>UrbanFuncionArea_class</grp:class>
							<grp:function>UrbanFuncionArea_function</grp:function>
							<grp:usage>UrbanFuncionArea_usage</grp:usage>
							<grp:geometry>
								<gml:MultiSurface gml:id="id_MultiSurf_ufa_1_6_3" srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
									<gml:surfaceMember>
										<gml:Polygon>
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>80 -50 0 120 -50 0 120 0 0 80 0 0 80 -50 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
								</gml:MultiSurface>
							</grp:geometry>
							<nrg3:type codeSpace="urbfuncarea_type_codeSpace">urbfuncarea_type_13</nrg3:type>
							<nrg3:code codeSpace="urbfuncarea_code_codeSpace">urbfuncarea_code_13</nrg3:code>
						</nrg3:UrbanFunctionArea>
					</grp:groupMember>
					<grp:groupMember>
						<nrg3:UrbanFunctionArea gml:id="id_urban_function_area_1_6_4">
							<gml:description>This is an UrbanFunctionArea of third level</gml:description>
							<gml:name>UrbanFunctionArea of third level</gml:name>
							<nrg3:referencePoint>
								<gml:Point srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
									<gml:pos>140 -75 0</gml:pos>
								</gml:Point>
							</nrg3:referencePoint>
							<grp:class>UrbanFuncionArea_class</grp:class>
							<grp:function>UrbanFuncionArea_function</grp:function>
							<grp:usage>UrbanFuncionArea_usage</grp:usage>
							<grp:geometry>
								<gml:MultiSurface gml:id="id_MultiSurf_ufa_1_6_4" srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
									<gml:surfaceMember>
										<gml:Polygon>
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>120 -100 0 160 -100 0 160 -50 0 120 -50 0 120 -100 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
								</gml:MultiSurface>
							</grp:geometry>
							<nrg3:type codeSpace="urbfuncarea_type_codeSpace">urbfuncarea_type_13</nrg3:type>
							<nrg3:code codeSpace="urbfuncarea_code_codeSpace">urbfuncarea_code_13</nrg3:code>
						</nrg3:UrbanFunctionArea>
					</grp:groupMember>
					<grp:geometry>
						<gml:MultiSurface gml:id="id_MultiSurf_ufa_1_6" srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
							<gml:surfaceMember>
								<gml:Polygon>
									<gml:exterior>
										<gml:LinearRing>
											<gml:posList>80 -100 0 160 -100 0 160 0 0 80 0 0 80 -100 0</gml:posList>
										</gml:LinearRing>
									</gml:exterior>
								</gml:Polygon>
							</gml:surfaceMember>
						</gml:MultiSurface>
					</grp:geometry>
					<nrg3:type codeSpace="urbfuncarea_type_codeSpace">urbfuncarea_type_12</nrg3:type>
					<nrg3:code codeSpace="urbfuncarea_code_codeSpace">urbfuncarea_code_12</nrg3:code>
				</nrg3:UrbanFunctionArea>
			</grp:groupMember>
			<grp:geometry>
				<gml:MultiSurface gml:id="id_MultiSurf_ufa_1" srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
					<gml:surfaceMember>
						<gml:Polygon>
							<gml:exterior>
								<gml:LinearRing>
									<gml:posList>-80 -100 0 160 -100 0 160 100 0 -80 100 0 -80 -100 0</gml:posList>
								</gml:LinearRing>
							</gml:exterior>
						</gml:Polygon>
					</gml:surfaceMember>
				</gml:MultiSurface>
			</grp:geometry>
			<nrg3:type codeSpace="urbfuncarea_type_codeSpace">urbfuncarea_type_1</nrg3:type>
			<nrg3:code codeSpace="urbfuncarea_code_codeSpace">urbfuncarea_code_1</nrg3:code>
		</nrg3:UrbanFunctionArea>
	</core:cityObjectMember>
	<app:appearanceMember>
		<app:Appearance gml:id="id_appearance_1">
			<gml:description>This is a global appearance for the Alderaan dataset</gml:description>
			<gml:name>Global Appearance of Alderaan test dataset</gml:name>
			<app:theme>Alderaan Urban Function Areas</app:theme>
			<app:surfaceDataMember>
				<app:X3DMaterial gml:id="X3DMaterial_UUID_16a34b5f-0db6-4829-8088-6f73a3007b6d">
					<gml:name>Colour Blue (BACK) UrbanFunctionArea Level 2-3</gml:name>
					<app:isFront>false</app:isFront>
					<app:diffuseColor>0 0 1</app:diffuseColor>
					<app:target>#id_MultiSurf_ufa_1_2</app:target>
					<app:target>#id_MultiSurf_ufa_1_4</app:target>
					<app:target>#id_MultiSurf_ufa_1_6</app:target>
					<app:target>#id_MultiSurf_ufa_1_1_4</app:target>
					<app:target>#id_MultiSurf_ufa_1_2_4</app:target>
					<app:target>#id_MultiSurf_ufa_1_3_4</app:target>
					<app:target>#id_MultiSurf_ufa_1_4_4</app:target>
					<app:target>#id_MultiSurf_ufa_1_5_4</app:target>
					<app:target>#id_MultiSurf_ufa_1_6_4</app:target>
				</app:X3DMaterial>
			</app:surfaceDataMember>
			<app:surfaceDataMember>
				<app:X3DMaterial gml:id="X3DMaterial_UUID_15a34b5f-0db6-4829-8088-6f73a3007b6d">
					<gml:name>Colour Blue (FRONT) UrbanFunctionArea Level 2-3</gml:name>
					<app:isFront>true</app:isFront>
					<app:diffuseColor>0 0 1</app:diffuseColor>
					<app:target>#id_MultiSurf_ufa_1_2</app:target>
					<app:target>#id_MultiSurf_ufa_1_4</app:target>
					<app:target>#id_MultiSurf_ufa_1_6</app:target>
					<app:target>#id_MultiSurf_ufa_1_1_4</app:target>
					<app:target>#id_MultiSurf_ufa_1_2_4</app:target>
					<app:target>#id_MultiSurf_ufa_1_3_4</app:target>
					<app:target>#id_MultiSurf_ufa_1_4_4</app:target>
					<app:target>#id_MultiSurf_ufa_1_5_4</app:target>
					<app:target>#id_MultiSurf_ufa_1_6_4</app:target>
				</app:X3DMaterial>
			</app:surfaceDataMember>
			<app:surfaceDataMember>
				<app:X3DMaterial gml:id="X3DMaterial_UUID_14a34b5f-0db6-4829-8088-6f73a3007b6d">
					<gml:name>Colour Green (BACK) UrbanFunctionArea Level 2-3</gml:name>
					<app:isFront>false</app:isFront>
					<app:diffuseColor>0 1 0</app:diffuseColor>
					<app:target>#id_MultiSurf_ufa_1_1</app:target>
					<app:target>#id_MultiSurf_ufa_1_3</app:target>
					<app:target>#id_MultiSurf_ufa_1_5</app:target>
					<app:target>#id_MultiSurf_ufa_1_1_3</app:target>
					<app:target>#id_MultiSurf_ufa_1_2_3</app:target>
					<app:target>#id_MultiSurf_ufa_1_3_3</app:target>
					<app:target>#id_MultiSurf_ufa_1_4_3</app:target>
					<app:target>#id_MultiSurf_ufa_1_5_3</app:target>
					<app:target>#id_MultiSurf_ufa_1_6_3</app:target>
				</app:X3DMaterial>
			</app:surfaceDataMember>
			<app:surfaceDataMember>
				<app:X3DMaterial gml:id="X3DMaterial_UUID_13a34b5f-0db6-4829-8088-6f73a3007b6d">
					<gml:name>Colour Green (FRONT) UrbanFunctionArea Level 2-3</gml:name>
					<app:isFront>true</app:isFront>
					<app:diffuseColor>0 1 0</app:diffuseColor>
					<app:target>#id_MultiSurf_ufa_1_1</app:target>
					<app:target>#id_MultiSurf_ufa_1_3</app:target>
					<app:target>#id_MultiSurf_ufa_1_5</app:target>
					<app:target>#id_MultiSurf_ufa_1_1_3</app:target>
					<app:target>#id_MultiSurf_ufa_1_2_3</app:target>
					<app:target>#id_MultiSurf_ufa_1_3_3</app:target>
					<app:target>#id_MultiSurf_ufa_1_4_3</app:target>
					<app:target>#id_MultiSurf_ufa_1_5_3</app:target>
					<app:target>#id_MultiSurf_ufa_1_6_3</app:target>
				</app:X3DMaterial>
			</app:surfaceDataMember>
			<app:surfaceDataMember>
				<app:X3DMaterial gml:id="X3DMaterial_UUID_12a34b5f-0db6-4829-8088-6f73a3007b6d">
					<gml:name>Colour Pink (BACK) UrbanFunctionArea Level 3</gml:name>
					<app:isFront>false</app:isFront>
					<app:diffuseColor>1 0.75 0.79</app:diffuseColor>
					<app:target>#id_MultiSurf_ufa_1_1_2</app:target>
					<app:target>#id_MultiSurf_ufa_1_2_2</app:target>
					<app:target>#id_MultiSurf_ufa_1_3_2</app:target>
					<app:target>#id_MultiSurf_ufa_1_4_2</app:target>
					<app:target>#id_MultiSurf_ufa_1_5_2</app:target>
					<app:target>#id_MultiSurf_ufa_1_6_2</app:target>
				</app:X3DMaterial>
			</app:surfaceDataMember>
			<app:surfaceDataMember>
				<app:X3DMaterial gml:id="X3DMaterial_UUID_11a34b5f-0db6-4829-8088-6f73a3007b6d">
					<gml:name>Colour Pink (FRONT) UrbanFunctionArea Level 3</gml:name>
					<app:isFront>true</app:isFront>
					<app:diffuseColor>1 0.75 0.79</app:diffuseColor>
					<app:target>#id_MultiSurf_ufa_1_1_2</app:target>
					<app:target>#id_MultiSurf_ufa_1_2_2</app:target>
					<app:target>#id_MultiSurf_ufa_1_3_2</app:target>
					<app:target>#id_MultiSurf_ufa_1_4_2</app:target>
					<app:target>#id_MultiSurf_ufa_1_5_2</app:target>
					<app:target>#id_MultiSurf_ufa_1_6_2</app:target>
				</app:X3DMaterial>
			</app:surfaceDataMember>
			<app:surfaceDataMember>
				<app:X3DMaterial gml:id="X3DMaterial_UUID_10a34b5f-0db6-4829-8088-6f73a3007b6d">
					<gml:name>Colour Red (BACK) UrbanFunctionArea Level 3</gml:name>
					<app:isFront>false</app:isFront>
					<app:diffuseColor>1 0 0</app:diffuseColor>
					<app:target>#id_MultiSurf_ufa_1_1_1</app:target>
					<app:target>#id_MultiSurf_ufa_1_2_1</app:target>
					<app:target>#id_MultiSurf_ufa_1_3_1</app:target>
					<app:target>#id_MultiSurf_ufa_1_4_1</app:target>
					<app:target>#id_MultiSurf_ufa_1_5_1</app:target>
					<app:target>#id_MultiSurf_ufa_1_6_1</app:target>
				</app:X3DMaterial>
			</app:surfaceDataMember>
			<app:surfaceDataMember>
				<app:X3DMaterial gml:id="X3DMaterial_UUID_9da34b5f-0db6-4829-8088-6f73a3007b6d">
					<gml:name>Colour Red (FRONT) UrbanFunctionArea Level 3</gml:name>
					<app:isFront>true</app:isFront>
					<app:diffuseColor>1 0 0</app:diffuseColor>
					<app:target>#id_MultiSurf_ufa_1_1_1</app:target>
					<app:target>#id_MultiSurf_ufa_1_2_1</app:target>
					<app:target>#id_MultiSurf_ufa_1_3_1</app:target>
					<app:target>#id_MultiSurf_ufa_1_4_1</app:target>
					<app:target>#id_MultiSurf_ufa_1_5_1</app:target>
					<app:target>#id_MultiSurf_ufa_1_6_1</app:target>
				</app:X3DMaterial>
			</app:surfaceDataMember>
			<app:surfaceDataMember>
				<app:X3DMaterial gml:id="X3DMaterial_UUID_8da34b5f-0db6-4829-8088-6f73a3007b6d">
					<gml:name>Colour Yellow (BACK) UrbanFunctionArea Level 1</gml:name>
					<app:isFront>true</app:isFront>
					<app:diffuseColor>1 1 0</app:diffuseColor>
					<app:target>#id_MultiSurf_ufa_1</app:target>
				</app:X3DMaterial>
			</app:surfaceDataMember>
			<app:surfaceDataMember>
				<app:X3DMaterial gml:id="X3DMaterial_UUID_7da34b5f-0db6-4829-8088-6f73a3007b6d">
					<gml:name>Colour Yellow (FRONT) UrbanFunctionArea Level 1</gml:name>
					<app:isFront>false</app:isFront>
					<app:diffuseColor>1 1 0</app:diffuseColor>
					<app:target>#id_MultiSurf_ufa_1</app:target>
				</app:X3DMaterial>
			</app:surfaceDataMember>
		</app:Appearance>
	</app:appearanceMember>
</core:CityModel>