<?xml version="1.0" encoding="UTF-8"?>
<!--
*******************************************************
*******************************************************

          READ ME

*******************************************************

CityGML 2.0 Test dataset "Alderaan"
with Energy ADE 2.0 Beta 7

Last update: 2025-05-11

** CityGML 2.0 **

This file contains 11 "ancillary" buildings, modelled in
- Lo0 multisurface
- LoD1 solid.

All buildings are part of a CityObjectGroup, which is modelled
via a multisurface geometry (corresponding to its
extents).

There is a global appearance.

** Energy ADE 2.0 **

The city object group and all buildings are modelled
also through a 3D reference point.

** Additional information

To visualise the data and explore the attributes,
you can use the freeware KIT ModelViewer.
You can download it from:

https://www.iai.kit.edu/1302.php

Please be aware that this dataset is intended for
testing purposes, so some attribute values might be
wrong or without any realistic physical meaning.

*******************************************************

This CityGML file was generated by:

Dr. Giorgio Agugiaro
3D Geoinformation group
Delft University of Technology
The Netherlands

https://3d.bk.tudelft.nl/gagugiaro/

*******************************************************
*******************************************************
-->
<core:CityModel xmlns:app="http://www.opengis.net/citygml/appearance/2.0" xmlns:bldg="http://www.opengis.net/citygml/building/2.0" xmlns:brid="http://www.opengis.net/citygml/bridge/2.0" xmlns:core="http://www.opengis.net/citygml/2.0" xmlns:dem="http://www.opengis.net/citygml/relief/2.0" xmlns:frn="http://www.opengis.net/citygml/cityfurniture/2.0" xmlns:gen="http://www.opengis.net/citygml/generics/2.0" xmlns:gml="http://www.opengis.net/gml" xmlns:grp="http://www.opengis.net/citygml/cityobjectgroup/2.0" xmlns:luse="http://www.opengis.net/citygml/landuse/2.0" xmlns:nrg2="http://www.citygml.org/ade/energy/2.0" xmlns:pbase="http://www.opengis.net/citygml/profiles/base/2.0" xmlns:sch="http://www.ascc.net/xml/schematron" xmlns:smil20="http://www.w3.org/2001/SMIL20/" xmlns:smil20lang="http://www.w3.org/2001/SMIL20/Language" xmlns:tex="http://www.opengis.net/citygml/texturedsurface/2.0" xmlns:tran="http://www.opengis.net/citygml/transportation/2.0" xmlns:tun="http://www.opengis.net/citygml/tunnel/2.0" xmlns:veg="http://www.opengis.net/citygml/vegetation/2.0" xmlns:wtr="http://www.opengis.net/citygml/waterbody/2.0" xmlns:xAL="urn:oasis:names:tc:ciq:xsdschema:xAL:2.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<gml:description>This city model contains a set of "fantasy" buildings created by Giorgio Agugiaro (g.agugiaro@tudelft.nl)</gml:description>
	<gml:name>CityGML city of Alderaan</gml:name>
	<gml:boundedBy>
		<gml:Envelope srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
			<gml:lowerCorner>-30 -50 -5</gml:lowerCorner>
			<gml:upperCorner>100 40 50</gml:upperCorner>
		</gml:Envelope>
	</gml:boundedBy>
	<core:cityObjectMember>
		<grp:CityObjectGroup gml:id="id_group_1">
			<gml:description>This group contains all "ancillary" buildings of CityGML city Alderaan</gml:description>
			<gml:name>Ancillary buildings group</gml:name>
			<nrg2:referencePoint>
				<gml:Point srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
					<gml:pos>35 -5 0</gml:pos>
				</gml:Point>
			</nrg2:referencePoint>
			<grp:groupMember>
				<bldg:Building gml:id="id_box_building_20">
					<gml:description>This is a simple, primastic building meant to provide shadowing and occlusions</gml:description>
					<gml:name>Box building 20</gml:name>
					<core:creationDate>2024-09-25</core:creationDate>
					<nrg2:referencePoint>
						<gml:Point srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
							<gml:pos>-15 10 5</gml:pos>
						</gml:Point>
					</nrg2:referencePoint>
					<bldg:lod0FootPrint>
						<gml:MultiSurface gml:id="id_lod0_MultiSurf_20" srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
							<gml:surfaceMember>
								<gml:Polygon gml:id="id_lod0_Polygon_20">
									<gml:exterior>
										<gml:LinearRing>
											<gml:posList>-20 5 0 -10 5 0 -10 15 0 -20 15 0 -20 5 0</gml:posList>
										</gml:LinearRing>
									</gml:exterior>
								</gml:Polygon>
							</gml:surfaceMember>
						</gml:MultiSurface>
					</bldg:lod0FootPrint>
					<bldg:lod1Solid>
						<gml:Solid gml:id="id_lod1_Solid_20" srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
							<gml:exterior>
								<gml:CompositeSurface gml:id="id_lod1_CompSurf_20">
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_1">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>-20 5 0 -20 15 0 -10 15 0 -10 5 0 -20 5 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_2">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>-20 5 0 -10 5 0 -10 5 10 -20 5 10 -20 5 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_3">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>-10 5 0 -10 15 0 -10 15 10 -10 5 10 -10 5 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_4">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>-10 15 0 -20 15 0 -20 15 10 -10 15 10 -10 15 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_5">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>-20 15 0 -20 5 0 -20 5 10 -20 15 10 -20 15 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_6">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>-20 5 10 -10 5 10 -10 15 10 -20 15 10 -20 5 10</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
								</gml:CompositeSurface>
							</gml:exterior>
						</gml:Solid>
					</bldg:lod1Solid>
				</bldg:Building>
			</grp:groupMember>
			<grp:groupMember>
				<bldg:Building gml:id="id_box_building_21">
					<gml:description>This is a simple, primastic building meant to provide shadowing and occlusions</gml:description>
					<gml:name>Box building 21</gml:name>
					<core:creationDate>2024-09-25</core:creationDate>
					<nrg2:referencePoint>
						<gml:Point srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
							<gml:pos>-15 -5 10</gml:pos>
						</gml:Point>
					</nrg2:referencePoint>
					<bldg:lod0FootPrint>
						<gml:MultiSurface gml:id="id_lod0_MultiSurf_21" srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
							<gml:surfaceMember>
								<gml:Polygon gml:id="id_lod0_Polygon_21">
									<gml:exterior>
										<gml:LinearRing>
											<gml:posList>-20 -10 0 -10 -10 0 -10 0 0 -20 0 0 -20 -10 0</gml:posList>
										</gml:LinearRing>
									</gml:exterior>
								</gml:Polygon>
							</gml:surfaceMember>
						</gml:MultiSurface>
					</bldg:lod0FootPrint>
					<bldg:lod1Solid>
						<gml:Solid gml:id="id_lod1_Solid_21" srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
							<gml:exterior>
								<gml:CompositeSurface gml:id="id_lod1_CompSurf_21">
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_7">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>-20 -10 0 -20 0 0 -10 0 0 -10 -10 0 -20 -10 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_8">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>-20 -10 0 -10 -10 0 -10 -10 20 -20 -10 20 -20 -10 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_9">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>-10 -10 0 -10 0 0 -10 0 20 -10 -10 20 -10 -10 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_10">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>-10 0 0 -20 0 0 -20 0 20 -10 0 20 -10 0 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_11">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>-20 0 0 -20 -10 0 -20 -10 20 -20 0 20 -20 0 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_12">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>-20 -10 20 -10 -10 20 -10 0 20 -20 0 20 -20 -10 20</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
								</gml:CompositeSurface>
							</gml:exterior>
						</gml:Solid>
					</bldg:lod1Solid>
				</bldg:Building>
			</grp:groupMember>
			<grp:groupMember>
				<bldg:Building gml:id="id_box_building_22">
					<gml:description>This is a simple, primastic building meant to provide shadowing and occlusions</gml:description>
					<gml:name>Box building 22</gml:name>
					<core:creationDate>2024-09-25</core:creationDate>
					<nrg2:referencePoint>
						<gml:Point srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
							<gml:pos>-25 -25 5</gml:pos>
						</gml:Point>
					</nrg2:referencePoint>
					<bldg:lod0FootPrint>
						<gml:MultiSurface gml:id="id_lod0_MultiSurf_22" srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
							<gml:surfaceMember>
								<gml:Polygon gml:id="id_lod0_Polygon_22">
									<gml:exterior>
										<gml:LinearRing>
											<gml:posList>-30 -30 0 -20 -30 0 -20 -20 0 -30 -20 0 -30 -30 0</gml:posList>
										</gml:LinearRing>
									</gml:exterior>
								</gml:Polygon>
							</gml:surfaceMember>
						</gml:MultiSurface>
					</bldg:lod0FootPrint>
					<bldg:lod1Solid>
						<gml:Solid gml:id="id_lod1_Solid_22" srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
							<gml:exterior>
								<gml:CompositeSurface gml:id="id_lod1_CompSurf_22">
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_13">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>-30 -30 0 -30 -20 0 -20 -20 0 -20 -30 0 -30 -30 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_14">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>-30 -30 0 -20 -30 0 -20 -30 10 -30 -30 10 -30 -30 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_15">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>-20 -30 0 -20 -20 0 -20 -20 10 -20 -30 10 -20 -30 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_16">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>-20 -20 0 -30 -20 0 -30 -20 10 -20 -20 10 -20 -20 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_17">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>-30 -20 0 -30 -30 0 -30 -30 10 -30 -20 10 -30 -20 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_18">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>-30 -30 10 -20 -30 10 -20 -20 10 -30 -20 10 -30 -30 10</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
								</gml:CompositeSurface>
							</gml:exterior>
						</gml:Solid>
					</bldg:lod1Solid>
				</bldg:Building>
			</grp:groupMember>
			<grp:groupMember>
				<bldg:Building gml:id="id_box_building_23">
					<gml:description>This is a simple, primastic building meant to provide shadowing and occlusions</gml:description>
					<gml:name>Box building 23</gml:name>
					<core:creationDate>2024-09-25</core:creationDate>
					<nrg2:referencePoint>
						<gml:Point srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
							<gml:pos>-25 -40 15</gml:pos>
						</gml:Point>
					</nrg2:referencePoint>
					<bldg:lod0FootPrint>
						<gml:MultiSurface gml:id="id_lod0_MultiSurf_23" srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
							<gml:surfaceMember>
								<gml:Polygon gml:id="id_lod0_Polygon_23">
									<gml:exterior>
										<gml:LinearRing>
											<gml:posList>-30 -45 0 -20 -45 0 -20 -35 0 -30 -35 0 -30 -45 0</gml:posList>
										</gml:LinearRing>
									</gml:exterior>
								</gml:Polygon>
							</gml:surfaceMember>
						</gml:MultiSurface>
					</bldg:lod0FootPrint>
					<bldg:lod1Solid>
						<gml:Solid gml:id="id_lod1_Solid_23" srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
							<gml:exterior>
								<gml:CompositeSurface gml:id="id_lod1_CompSurf_23">
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_19">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>-30 -45 0 -30 -35 0 -20 -35 0 -20 -45 0 -30 -45 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_20">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>-30 -45 0 -20 -45 0 -20 -45 30 -30 -45 30 -30 -45 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_21">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>-20 -45 0 -20 -35 0 -20 -35 30 -20 -45 30 -20 -45 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_22">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>-20 -35 0 -30 -35 0 -30 -35 30 -20 -35 30 -20 -35 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_23">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>-30 -35 0 -30 -45 0 -30 -45 30 -30 -35 30 -30 -35 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_24">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>-30 -45 30 -20 -45 30 -20 -35 30 -30 -35 30 -30 -45 30</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
								</gml:CompositeSurface>
							</gml:exterior>
						</gml:Solid>
					</bldg:lod1Solid>
				</bldg:Building>
			</grp:groupMember>
			<grp:groupMember>
				<bldg:Building gml:id="id_box_building_24">
					<gml:description>This is a simple, primastic building meant to provide shadowing and occlusions</gml:description>
					<gml:name>Box building 24</gml:name>
					<core:creationDate>2024-09-25</core:creationDate>
					<nrg2:referencePoint>
						<gml:Point srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
							<gml:pos>65 -45 5</gml:pos>
						</gml:Point>
					</nrg2:referencePoint>
					<bldg:lod0FootPrint>
						<gml:MultiSurface gml:id="id_lod0_MultiSurf_24" srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
							<gml:surfaceMember>
								<gml:Polygon gml:id="id_lod0_Polygon_24">
									<gml:exterior>
										<gml:LinearRing>
											<gml:posList>60 -50 0 70 -50 0 70 -40 0 60 -40 0 60 -50 0</gml:posList>
										</gml:LinearRing>
									</gml:exterior>
								</gml:Polygon>
							</gml:surfaceMember>
						</gml:MultiSurface>
					</bldg:lod0FootPrint>
					<bldg:lod1Solid>
						<gml:Solid gml:id="id_lod1_Solid_24" srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
							<gml:exterior>
								<gml:CompositeSurface gml:id="id_lod1_CompSurf_24">
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_25">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>60 -50 0 60 -40 0 70 -40 0 70 -50 0 60 -50 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_26">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>60 -50 0 70 -50 0 70 -50 10 60 -50 10 60 -50 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_27">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>70 -50 0 70 -40 0 70 -40 10 70 -50 10 70 -50 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_28">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>70 -40 0 60 -40 0 60 -40 10 70 -40 10 70 -40 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_29">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>60 -40 0 60 -50 0 60 -50 10 60 -40 10 60 -40 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_30">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>60 -50 10 70 -50 10 70 -40 10 60 -40 10 60 -50 10</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
								</gml:CompositeSurface>
							</gml:exterior>
						</gml:Solid>
					</bldg:lod1Solid>
				</bldg:Building>
			</grp:groupMember>
			<grp:groupMember>
				<bldg:Building gml:id="id_box_building_25">
					<gml:description>This is a simple, primastic building meant to provide shadowing and occlusions</gml:description>
					<gml:name>Box building 25</gml:name>
					<core:creationDate>2024-09-25</core:creationDate>
					<nrg2:referencePoint>
						<gml:Point srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
							<gml:pos>50 -45 7.5</gml:pos>
						</gml:Point>
					</nrg2:referencePoint>
					<bldg:lod0FootPrint>
						<gml:MultiSurface gml:id="id_lod0_MultiSurf_25" srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
							<gml:surfaceMember>
								<gml:Polygon gml:id="id_lod0_Polygon_25">
									<gml:exterior>
										<gml:LinearRing>
											<gml:posList>45 -50 0 55 -50 0 55 -40 0 45 -40 0 45 -50 0</gml:posList>
										</gml:LinearRing>
									</gml:exterior>
								</gml:Polygon>
							</gml:surfaceMember>
						</gml:MultiSurface>
					</bldg:lod0FootPrint>
					<bldg:lod1Solid>
						<gml:Solid gml:id="id_lod1_Solid_25" srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
							<gml:exterior>
								<gml:CompositeSurface gml:id="id_lod1_CompSurf_25">
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_31">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>45 -50 0 45 -40 0 55 -40 0 55 -50 0 45 -50 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_32">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>45 -50 0 55 -50 0 55 -50 15 45 -50 15 45 -50 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_33">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>55 -50 0 55 -40 0 55 -40 15 55 -50 15 55 -50 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_34">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>55 -40 0 45 -40 0 45 -40 15 55 -40 15 55 -40 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_35">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>45 -40 0 45 -50 0 45 -50 15 45 -40 15 45 -40 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_36">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>45 -50 15 55 -50 15 55 -40 15 45 -40 15 45 -50 15</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
								</gml:CompositeSurface>
							</gml:exterior>
						</gml:Solid>
					</bldg:lod1Solid>
				</bldg:Building>
			</grp:groupMember>
			<grp:groupMember>
				<bldg:Building gml:id="id_box_building_26">
					<gml:description>This is a simple, primastic building meant to provide shadowing and occlusions</gml:description>
					<gml:name>Box building 26</gml:name>
					<core:creationDate>2024-09-25</core:creationDate>
					<nrg2:referencePoint>
						<gml:Point srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
							<gml:pos>85 0 5</gml:pos>
						</gml:Point>
					</nrg2:referencePoint>
					<bldg:lod0FootPrint>
						<gml:MultiSurface gml:id="id_lod0_MultiSurf_26" srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
							<gml:surfaceMember>
								<gml:Polygon gml:id="id_lod0_Polygon_26">
									<gml:exterior>
										<gml:LinearRing>
											<gml:posList>80 -5 0 90 -5 0 90 5 0 80 5 0 80 -5 0</gml:posList>
										</gml:LinearRing>
									</gml:exterior>
								</gml:Polygon>
							</gml:surfaceMember>
						</gml:MultiSurface>
					</bldg:lod0FootPrint>
					<bldg:lod1Solid>
						<gml:Solid gml:id="id_lod1_Solid_26" srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
							<gml:exterior>
								<gml:CompositeSurface gml:id="id_lod1_CompSurf_26">
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_37">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>80 -5 0 80 5 0 90 5 0 90 -5 0 80 -5 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_38">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>80 -5 0 90 -5 0 90 -5 10 80 -5 10 80 -5 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_39">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>90 -5 0 90 5 0 90 5 10 90 -5 10 90 -5 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_40">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>90 5 0 80 5 0 80 5 10 90 5 10 90 5 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_41">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>80 5 0 80 -5 0 80 -5 10 80 5 10 80 5 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_42">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>80 -5 10 90 -5 10 90 5 10 80 5 10 80 -5 10</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
								</gml:CompositeSurface>
							</gml:exterior>
						</gml:Solid>
					</bldg:lod1Solid>
				</bldg:Building>
			</grp:groupMember>
			<grp:groupMember>
				<bldg:Building gml:id="id_box_building_27">
					<gml:description>This is a simple, primastic building meant to provide shadowing and occlusions</gml:description>
					<gml:name>Box building 27</gml:name>
					<core:creationDate>2024-09-25</core:creationDate>
					<nrg2:referencePoint>
						<gml:Point srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
							<gml:pos>0 25 5</gml:pos>
						</gml:Point>
					</nrg2:referencePoint>
					<bldg:lod0FootPrint>
						<gml:MultiSurface gml:id="id_lod0_MultiSurf_27" srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
							<gml:surfaceMember>
								<gml:Polygon gml:id="id_lod0_Polygon_27">
									<gml:exterior>
										<gml:LinearRing>
											<gml:posList>-10 20 -5 10 20 -5 10 30 -5 -10 30 -5 -10 20 -5</gml:posList>
										</gml:LinearRing>
									</gml:exterior>
								</gml:Polygon>
							</gml:surfaceMember>
						</gml:MultiSurface>
					</bldg:lod0FootPrint>
					<bldg:lod1Solid>
						<gml:Solid gml:id="id_lod1_Solid_27" srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
							<gml:exterior>
								<gml:CompositeSurface gml:id="id_lod1_CompSurf_27">
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_43">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>-10 20 -5 -10 30 -5 10 30 -5 10 20 -5 -10 20 -5</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_44">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>-10 20 -5 10 20 -5 10 20 15 -10 20 15 -10 20 -5</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_45">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>10 20 -5 10 30 -5 10 30 15 10 20 15 10 20 -5</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_46">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>10 30 -5 -10 30 -5 -10 30 15 10 30 15 10 30 -5</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_47">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>-10 30 -5 -10 20 -5 -10 20 15 -10 30 15 -10 30 -5</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_48">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>-10 20 15 10 20 15 10 30 15 -10 30 15 -10 20 15</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
								</gml:CompositeSurface>
							</gml:exterior>
						</gml:Solid>
					</bldg:lod1Solid>
				</bldg:Building>
			</grp:groupMember>
			<grp:groupMember>
				<bldg:Building gml:id="id_box_building_28">
					<gml:description>This is a simple, primastic building meant to provide shadowing and occlusions</gml:description>
					<gml:name>Box building 28</gml:name>
					<core:creationDate>2024-09-25</core:creationDate>
					<nrg2:referencePoint>
						<gml:Point srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
							<gml:pos>50 35 15</gml:pos>
						</gml:Point>
					</nrg2:referencePoint>
					<bldg:lod0FootPrint>
						<gml:MultiSurface gml:id="id_lod0_MultiSurf_28" srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
							<gml:surfaceMember>
								<gml:Polygon gml:id="id_lod0_Polygon_28">
									<gml:exterior>
										<gml:LinearRing>
											<gml:posList>40 30 0 60 30 0 60 40 0 40 40 0 40 30 0</gml:posList>
										</gml:LinearRing>
									</gml:exterior>
								</gml:Polygon>
							</gml:surfaceMember>
						</gml:MultiSurface>
					</bldg:lod0FootPrint>
					<bldg:lod1Solid>
						<gml:Solid gml:id="id_lod1_Solid_28" srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
							<gml:exterior>
								<gml:CompositeSurface gml:id="id_lod1_CompSurf_28">
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_49">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>40 30 0 40 40 0 60 40 0 60 30 0 40 30 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_50">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>40 30 0 60 30 0 60 30 30 40 30 30 40 30 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_51">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>60 30 0 60 40 0 60 40 30 60 30 30 60 30 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_52">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>60 40 0 40 40 0 40 40 30 60 40 30 60 40 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_53">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>40 40 0 40 30 0 40 30 30 40 40 30 40 40 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_54">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>40 30 30 60 30 30 60 40 30 40 40 30 40 30 30</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
								</gml:CompositeSurface>
							</gml:exterior>
						</gml:Solid>
					</bldg:lod1Solid>
				</bldg:Building>
			</grp:groupMember>
			<grp:groupMember>
				<bldg:Building gml:id="id_box_building_29">
					<gml:description>This is a simple, primastic building meant to provide shadowing and occlusions</gml:description>
					<gml:name>Box building 29</gml:name>
					<core:creationDate>2024-09-25</core:creationDate>
					<nrg2:referencePoint>
						<gml:Point srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
							<gml:pos>30 -45 15</gml:pos>
						</gml:Point>
					</nrg2:referencePoint>
					<bldg:lod0FootPrint>
						<gml:MultiSurface gml:id="id_lod0_MultiSurf_29" srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
							<gml:surfaceMember>
								<gml:Polygon gml:id="id_lod0_Polygon_29">
									<gml:exterior>
										<gml:LinearRing>
											<gml:posList>20 -50 5 40 -50 5 40 -40 5 20 -40 5 20 -50 5</gml:posList>
										</gml:LinearRing>
									</gml:exterior>
								</gml:Polygon>
							</gml:surfaceMember>
						</gml:MultiSurface>
					</bldg:lod0FootPrint>
					<bldg:lod1Solid>
						<gml:Solid gml:id="id_lod1_Solid_29" srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
							<gml:exterior>
								<gml:CompositeSurface gml:id="id_lod1_CompSurf_29">
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_55">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>20 -50 5 20 -40 5 40 -40 5 40 -50 5 20 -50 5</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_56">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>20 -50 5 40 -50 5 40 -50 25 20 -50 25 20 -50 5</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_57">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>40 -50 5 40 -40 5 40 -40 25 40 -50 25 40 -50 5</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_58">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>40 -40 5 20 -40 5 20 -40 25 40 -40 25 40 -40 5</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_59">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>20 -40 5 20 -50 5 20 -50 25 20 -40 25 20 -40 5</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_60">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>20 -50 25 40 -50 25 40 -40 25 20 -40 25 20 -50 25</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
								</gml:CompositeSurface>
							</gml:exterior>
						</gml:Solid>
					</bldg:lod1Solid>
				</bldg:Building>
			</grp:groupMember>
			<grp:groupMember>
				<bldg:Building gml:id="id_box_building_30">
					<gml:description>This is a simple, primastic building meant to provide shadowing and occlusions</gml:description>
					<gml:name>Box building 30</gml:name>
					<core:creationDate>2024-09-25</core:creationDate>
					<nrg2:referencePoint>
						<gml:Point srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
							<gml:pos>95 -30 25</gml:pos>
						</gml:Point>
					</nrg2:referencePoint>
					<bldg:lod0FootPrint>
						<gml:MultiSurface gml:id="id_lod0_MultiSurf_30" srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
							<gml:surfaceMember>
								<gml:Polygon gml:id="id_lod0_Polygon_30">
									<gml:exterior>
										<gml:LinearRing>
											<gml:posList>90 -40 0 100 -40 0 100 -20 0 90 -20 0 90 -40 0</gml:posList>
										</gml:LinearRing>
									</gml:exterior>
								</gml:Polygon>
							</gml:surfaceMember>
						</gml:MultiSurface>
					</bldg:lod0FootPrint>
					<bldg:lod1Solid>
						<gml:Solid gml:id="id_lod1_Solid_30" srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
							<gml:exterior>
								<gml:CompositeSurface gml:id="id_lod1_CompSurf_30">
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_61">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>90 -40 0 90 -20 0 100 -20 0 100 -40 0 90 -40 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_62">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>90 -40 0 100 -40 0 100 -40 50 90 -40 50 90 -40 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_63">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>100 -40 0 100 -20 0 100 -20 50 100 -40 50 100 -40 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_64">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>100 -20 0 90 -20 0 90 -20 50 100 -20 50 100 -20 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_65">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>90 -20 0 90 -40 0 90 -40 50 90 -20 50 90 -20 0</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
									<gml:surfaceMember>
										<gml:Polygon gml:id="id_lod1_Polygon_66">
											<gml:exterior>
												<gml:LinearRing>
													<gml:posList>90 -40 50 100 -40 50 100 -20 50 90 -20 50 90 -40 50</gml:posList>
												</gml:LinearRing>
											</gml:exterior>
										</gml:Polygon>
									</gml:surfaceMember>
								</gml:CompositeSurface>
							</gml:exterior>
						</gml:Solid>
					</bldg:lod1Solid>
				</bldg:Building>
			</grp:groupMember>
			<grp:geometry>
				<gml:MultiSurface gml:id="MultiSurf_UUID_fbcd26a1-ae6a-4799-8b62-26622705b9bd" srsName="urn:ogc:def:crs,crs:EPSG::28992,crs:EPSG::5109" srsDimension="3">
					<gml:surfaceMember>
						<gml:Polygon>
							<gml:exterior>
								<gml:LinearRing>
									<gml:posList>-30 -50 0 100 -50 0 100 40 0 -30 40 0 -30 -50 0</gml:posList>
								</gml:LinearRing>
							</gml:exterior>
						</gml:Polygon>
					</gml:surfaceMember>
				</gml:MultiSurface>
			</grp:geometry>
		</grp:CityObjectGroup>
	</core:cityObjectMember>
	<app:appearanceMember>
		<app:Appearance gml:id="id_appearance_1">
			<gml:description>This is a global appearance for the Alderaan dataset</gml:description>
			<gml:name>Global Appearance of Alderaan test dataset</gml:name>
			<app:theme>Alderaan Colours</app:theme>
			<app:surfaceDataMember>
				<app:X3DMaterial gml:id="X3DMaterial_UUID_c57c2767-406b-40d5-a806-b6bd99dfb513">
					<gml:description>This is Colour Cyan (FRONT) for Ancillary Buildings LoD0</gml:description>
					<gml:name>Colour Cyan (FRONT) Ancillary Buildings LoD0</gml:name>
					<app:isFront>true</app:isFront>
					<app:diffuseColor>0 1 1</app:diffuseColor>
					<app:transparency>0</app:transparency>
					<app:target>#id_lod0_MultiSurf_20</app:target>
					<app:target>#id_lod0_MultiSurf_21</app:target>
					<app:target>#id_lod0_MultiSurf_22</app:target>
					<app:target>#id_lod0_MultiSurf_23</app:target>
					<app:target>#id_lod0_MultiSurf_24</app:target>
					<app:target>#id_lod0_MultiSurf_25</app:target>
					<app:target>#id_lod0_MultiSurf_26</app:target>
					<app:target>#id_lod0_MultiSurf_27</app:target>
					<app:target>#id_lod0_MultiSurf_28</app:target>
					<app:target>#id_lod0_MultiSurf_29</app:target>
					<app:target>#id_lod0_MultiSurf_30</app:target>
				</app:X3DMaterial>
			</app:surfaceDataMember>
			<app:surfaceDataMember>
				<app:X3DMaterial gml:id="X3DMaterial_UUID_67ca2e94-b751-4c84-bc73-c8f9f9745a16">
					<gml:description>This is Colour Cyan (BACK) for Ancillary Buildings LoD0</gml:description>
					<gml:name>Colour Cyan (BACK) Ancillary Buildings LoD0</gml:name>
					<app:isFront>false</app:isFront>
					<app:diffuseColor>0 1 1</app:diffuseColor>
					<app:transparency>0</app:transparency>
					<app:target>#id_lod0_MultiSurf_20</app:target>
					<app:target>#id_lod0_MultiSurf_21</app:target>
					<app:target>#id_lod0_MultiSurf_22</app:target>
					<app:target>#id_lod0_MultiSurf_23</app:target>
					<app:target>#id_lod0_MultiSurf_24</app:target>
					<app:target>#id_lod0_MultiSurf_25</app:target>
					<app:target>#id_lod0_MultiSurf_26</app:target>
					<app:target>#id_lod0_MultiSurf_27</app:target>
					<app:target>#id_lod0_MultiSurf_28</app:target>
					<app:target>#id_lod0_MultiSurf_29</app:target>
					<app:target>#id_lod0_MultiSurf_30</app:target>
				</app:X3DMaterial>
			</app:surfaceDataMember>
			<app:surfaceDataMember>
				<app:X3DMaterial gml:id="X3DMaterial_UUID_bc69ed4d-dee3-4530-af04-a52d1a3b7069">
					<gml:description>This is Colour Cyan (FRONT) for Ancillary Buildings LoD1</gml:description>
					<gml:name>Colour Cyan (FRONT) Ancillary Buildings LoD1</gml:name>
					<app:isFront>true</app:isFront>
					<app:diffuseColor>0 1 1</app:diffuseColor>
					<app:transparency>0.7</app:transparency>
					<app:target>#id_lod1_Solid_20</app:target>
					<app:target>#id_lod1_Solid_21</app:target>
					<app:target>#id_lod1_Solid_22</app:target>
					<app:target>#id_lod1_Solid_23</app:target>
					<app:target>#id_lod1_Solid_24</app:target>
					<app:target>#id_lod1_Solid_25</app:target>
					<app:target>#id_lod1_Solid_26</app:target>
					<app:target>#id_lod1_Solid_27</app:target>
					<app:target>#id_lod1_Solid_28</app:target>
					<app:target>#id_lod1_Solid_29</app:target>
					<app:target>#id_lod1_Solid_30</app:target>
				</app:X3DMaterial>
			</app:surfaceDataMember>
			<app:surfaceDataMember>
				<app:X3DMaterial gml:id="X3DMaterial_UUID_0c2ec2a5-4c7e-451e-85c0-8c275dacdff5">
					<gml:description>This is Colour Cyan (BACK) for Ancillary Buildings LoD1</gml:description>
					<gml:name>Colour Cyan (BACK) Ancillary Buildings LoD1</gml:name>
					<app:isFront>false</app:isFront>
					<app:diffuseColor>0 1 1</app:diffuseColor>
					<app:transparency>0.7</app:transparency>
					<app:target>#id_lod1_Solid_20</app:target>
					<app:target>#id_lod1_Solid_21</app:target>
					<app:target>#id_lod1_Solid_22</app:target>
					<app:target>#id_lod1_Solid_23</app:target>
					<app:target>#id_lod1_Solid_24</app:target>
					<app:target>#id_lod1_Solid_25</app:target>
					<app:target>#id_lod1_Solid_26</app:target>
					<app:target>#id_lod1_Solid_27</app:target>
					<app:target>#id_lod1_Solid_28</app:target>
					<app:target>#id_lod1_Solid_29</app:target>
					<app:target>#id_lod1_Solid_30</app:target>
				</app:X3DMaterial>
			</app:surfaceDataMember>
		</app:Appearance>
	</app:appearanceMember>
</core:CityModel>